limenius_react:
    # Other options are "server_side" and "client_side"
    default_rendering: 3
    serverside_rendering:
        # In case of error in server-side rendering, throw exception
        fail_loud: false
        # Replay every console.log message produced during server-side rendering
        # in the JavaScript console
        # Note that if enabled it will throw a (harmless) React warning
        trace: false
        server_bundle_path: null
        server_socket_path: "http://localhost:3000"
