my_online_store_react:
    # Options are "server_side", "client_side" and "both" (default)
    default_rendering: "both"
    serverside_rendering:
        # In case of error in server-side rendering, throw exception
        fail_loud: true
        # Replay every console.log message produced during server-side rendering
        # in the JavaScript console
        # Note that if enabled it will throw a (harmless) React warning
        trace: true
