version: '3.7'

services:
  symfony:
    build: .
    ports:
      - "8000:8000"
    volumes:
     - ./:/srv/app
#    entrypoint: [ "bash", "-c", "sleep 10 && node ./external-server.js"]

  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    expose: [3306:3306]
    volumes:
      - mydb:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'sfreact'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sfreact'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'sfreact'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'sfreact'

volumes:
  mydb:
