name: Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Check-PHP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          extensions: bcmath, exif, gd, gmp, imagick, intl, mysqli, opcache, pcntl, pdo_mysql, redis, soap, sockets, tidy, zip
          ini-values: date.timezone=Europe/Amsterdam, assert.exception=1, zend.assertions=1
      - uses: ramsey/composer-install@v2

      - name: Lint Twig
        run: bin/console lint:twig templates

      - name: Lint PHP
        run: composer lint

      - name: Coding Standards
        run: composer cs
